/**
 * MazeGameLayoutConstants.ts
 *
 * View layout, typography, and shared chrome dimensions (screen margins, arrows, fonts).
 * Physics and simulation values remain in model/MazeGameConstants.ts.
 */

const MazeGameLayoutConstants = {
  SCREEN_MARGIN: 14,
  RIGHT_COLUMN_WIDTH: 240,
  RIGHT_COLUMN_GAP: 10,

  // Vector arrows on the arena (model-space vectors drawn in the play area).
  ARENA_ARROW_HEAD_WIDTH: 12,
  ARENA_ARROW_HEAD_HEIGHT: 12,
  ARENA_ARROW_TAIL_WIDTH: 4,
  ARENA_ARROW_TILE_LENGTHS: 2.0,
  ARENA_ARROW_MIN_MAGNITUDE: 0.01,

  // Vector arrow on the control-pad (slightly larger for legibility at pad scale).
  PAD_ARROW_HEAD_WIDTH: 14,
  PAD_ARROW_HEAD_HEIGHT: 14,
  PAD_ARROW_TAIL_WIDTH: 5,

  CONTROL_PANEL_TITLE_FONT_SIZE: 16,
  CONTROL_PANEL_TAB_FONT_SIZE: 13,
  CONTROL_PANEL_KNOB_RADIUS: 9,
  CONTROL_PANEL_TAB_SPACING: 4,
  CONTROL_PANEL_PAD_CORNER_RADIUS: 4,
  CONTROL_PANEL_VBOX_SPACING: 8,

  HUD_VALUE_FONT_SIZE: 14,
  HUD_WARNING_FONT_SIZE: 12,
  HUD_COLLISION_MARKER_FONT_SIZE: 16,
  HUD_HBOX_SPACING: 6,
  HUD_VBOX_SPACING: 6,
  HUD_CLOCK_ICON_RADIUS: 11,
  HUD_COLLISIONS_MAX: 9999,

  ARENA_GOAL_FONT_SIZE: 22,
  ARENA_WIN_RING_RADIUS_FACTOR: 0.6,
  ARENA_WALL_LINE_WIDTH: 1,
  ARENA_WALL_CORNER_RADIUS: 2,
  ARENA_GOAL_CORNER_RADIUS: 3,
  ARENA_GOAL_SHEEN_FADE_STOP: 0.55,
  ARENA_WIN_PULSE_MIN_SCALE: 0.6,
  ARENA_WIN_PULSE_MAX_SCALE: 1.8,
  ARENA_TRACE_LINE_WIDTH: 2,

  // Procedural brick-wall texture (canvas pattern).
  ARENA_BRICK_PATTERN_MIN_UNIT_PX: 12,
  ARENA_BRICK_MORTAR_RATIO: 0.09,
  ARENA_BRICK_ROW_COUNT: 2,
  ARENA_BRICK_HIGHLIGHT_FACTOR: 0.18,
  ARENA_BRICK_SHADE_FACTOR: 0.14,
  ARENA_BRICK_TOP_BAND_RATIO: 0.22,
  ARENA_BRICK_BOTTOM_BAND_RATIO: 0.12,
  ARENA_BRICK_ROW_OFFSET_RATIO: 0.22,

  // Glossy particle sphere (ratios of view radius).
  ARENA_PARTICLE_BODY_STROKE_RATIO: 0.08,
  ARENA_PARTICLE_GLOW_RADIUS_RATIO: 1.35,
  ARENA_PARTICLE_GLOW_GRADIENT_INNER_RATIO: 0.2,
  ARENA_PARTICLE_GLOW_GRADIENT_OUTER_RATIO: 1.45,
  ARENA_PARTICLE_SPECULAR_RADIUS_RATIO: 0.22,
  ARENA_PARTICLE_SPECULAR_OFFSET_X_RATIO: 0.28,
  ARENA_PARTICLE_SPECULAR_OFFSET_Y_RATIO: 0.32,
  ARENA_PARTICLE_RADIAL_HIGHLIGHT_OFFSET_RATIO: 0.28,
  ARENA_PARTICLE_RADIAL_STOP_HIGHLIGHT: 0,
  ARENA_PARTICLE_RADIAL_STOP_BODY: 0.35,
  ARENA_PARTICLE_RADIAL_STOP_SHADE: 0.85,
  ARENA_PARTICLE_RADIAL_STOP_STROKE: 1,

  // Goal-tile overlay (rings, star, diagonal stripes).
  ARENA_GOAL_RING_STROKE_RATIO: 0.04,
  ARENA_GOAL_RING_RADIUS_RATIOS: [0.42, 0.28, 0.14] as const,
  ARENA_GOAL_STAR_RADIUS_RATIO: 0.2,
  ARENA_GOAL_STAR_INNER_RADIUS_RATIO: 0.45,
  ARENA_GOAL_STAR_STROKE_RATIO: 0.03,
  ARENA_GOAL_STRIPE_WIDTH_RATIO: 0.07,
  ARENA_GOAL_STRIPE_START_X_RATIOS: [-0.35, 0.35] as const,
  ARENA_GOAL_STRIPE_END_X_RATIOS: [0.65, 1.35] as const,

  PREFERENCES_LABEL_FONT_SIZE: 16,
  PREFERENCES_LABEL_MAX_WIDTH: 360,
  PREFERENCES_CONTROL_SPACING: 12,
  PREFERENCES_TOGGLE_SWITCH_WIDTH: 36,
  PREFERENCES_TOGGLE_SWITCH_HEIGHT: 18,

  LEVEL_SELECTOR_TITLE_FONT_SIZE: 14,
  LEVEL_SELECTOR_LABEL_FONT_SIZE: 13,
  LEVEL_SELECTOR_RADIO_BUTTON_RADIUS: 7,
  LEVEL_SELECTOR_RADIO_BUTTON_SPACING: 4,
  LEVEL_SELECTOR_VBOX_SPACING: 6,

  INFO_DIALOG_FONT_SIZE: 18,
  INFO_DIALOG_TITLE_FONT_SIZE: 22,
  INFO_DIALOG_VBOX_SPACING: 16,
  INFO_DIALOG_MAX_CONTENT_WIDTH_FRACTION: 0.75,
  INFO_BUTTON_SCALE: 0.5,

  FONT_WEIGHT_BOLD: "bold",
} as const;

export default MazeGameLayoutConstants;
